src/main/java/com/example/bucketplace/domain/product/entity/Product.java
src/main/java/com/example/bucketplace/domain/review/entity/Review.java

* #2 
* 상품 엔티티에 무료 배송, 특가 필드 추가
* 리뷰 엔티티에 평점 필드 추가

feat: 상품, 리뷰 엔티티 항목 추가

---

src/main/java/com/example/bucketplace/domain/member/controller/MemberController.java
src/main/java/com/example/bucketplace/domain/member/dto/MemberRequestDto.java
src/main/java/com/example/bucketplace/domain/member/dto/MemberResponseDto.java
src/main/java/com/example/bucketplace/domain/member/repository/MemberRepository.java
src/main/java/com/example/bucketplace/domain/member/service/MemberService.java
src/main/java/com/example/bucketplace/global/config/SecurityConfig.java
src/main/java/com/example/bucketplace/global/exception/ErrorCode.java

* #4 
- 회원가입 기능 구현
- 비밀번호 암호화
- 비밀번호 정규식 추가 (영문, 숫자 포함 8자 이상)
- 중복 이메일, 닉네임 검사
- 비밀번호, 비밀번호 확인 일치 검사

feat: 회원가입 기능 추가

---

src/main/java/com/example/bucketplace/domain/member/dto/MemberRequestDto.java
src/main/java/com/example/bucketplace/domain/member/dto/MemberResponseDto.java
src/main/java/com/example/bucketplace/domain/member/entity/RefreshToken.java
src/main/java/com/example/bucketplace/domain/member/repository/MemberRepository.java
src/main/java/com/example/bucketplace/domain/member/repository/RefreshTokenRepository.java
src/main/java/com/example/bucketplace/global/config/SecurityConfig.java
src/main/java/com/example/bucketplace/global/exception/ErrorCode.java
src/main/java/com/example/bucketplace/global/jwt/TokenProvider.java
src/main/java/com/example/bucketplace/global/security/JwtAuthenticationFilter.java
src/main/java/com/example/bucketplace/global/security/JwtAuthorizationFilter.java
src/main/java/com/example/bucketplace/global/security/UserDetailsImpl.java
src/main/java/com/example/bucketplace/global/security/UserDetailsServiceImpl.java
src/main/java/com/example/bucketplace/global/util/CustomResponseUtil.java

* #7 
- 로그인 기능 구현
- 액세스 토큰 발급, 헤더에 적용, 10분
- 리프레쉬 토큰 발급, 쿠키에 적용, 7일 (Redis)
* 로그아웃 기능을 추가해야 합니다.
* 토큰 재발행 기능을 추가해야 합니다.

feat: 로그인 기능 추가

---

src/main/java/com/example/bucketplace/domain/review/dto/ReviewRequestDto.java
src/main/java/com/example/bucketplace/domain/review/dto/ReviewResponseDto.java

feat: 리뷰 초기 설정

---

src/main/java/com/example/bucketplace/domain/member/controller/MemberController.java
src/main/java/com/example/bucketplace/domain/member/service/MemberService.java
src/main/java/com/example/bucketplace/global/config/SecurityConfig.java
src/main/java/com/example/bucketplace/global/exception/CustomExceptionHandler.java
src/main/java/com/example/bucketplace/global/exception/ErrorCode.java
src/main/java/com/example/bucketplace/global/exception/RefreshTokenException.java

* #10 
- 토큰 재발행 기능 추가
- 쿠키 값을 이용해서 액세스, 리프레쉬 토큰 재발행

feat: 토큰 재발행 추가

---

src/main/java/com/example/bucketplace/domain/member/controller/MemberController.java
src/main/java/com/example/bucketplace/domain/member/service/MemberService.java
src/main/java/com/example/bucketplace/global/config/SecurityConfig.java

* #11 
- 로그아웃 기능 추가
- 로그아웃 시 redis에 저장된 refresh token 제거
- 로그아웃 시 cookie에 저장된 refresh token 제거

feat: 로그아웃 기능 추가

---

src/main/java/com/example/bucketplace/domain/member/controller/MemberController.java
src/main/java/com/example/bucketplace/domain/member/controller/docs/MemberControllerDocs.java
src/main/java/com/example/bucketplace/domain/member/dto/MemberRequestDto.java

* #16 
- 회원 인증 관련 문서화 작업
- 회원가입, 토큰 재발행, 로그아웃 Swagger 설정

feat: 회원 인증 관련 문서화 작업

---

src/main/java/com/example/bucketplace/domain/member/controller/MemberController.java
src/main/java/com/example/bucketplace/domain/member/controller/docs/MemberControllerDocs.java
src/main/java/com/example/bucketplace/domain/member/dto/MemberResponseDto.java
src/main/java/com/example/bucketplace/domain/member/service/MemberService.java
src/main/java/com/example/bucketplace/global/config/SecurityConfig.java
src/main/java/com/example/bucketplace/global/exception/ErrorCode.java

* #18 
- 중복 검사 기능 추가
- 이메일과 닉네임 중복 검사 가능
- 값이 존재할 경우 isExist = true 반환, 없을 경우 false 반환
- 스웨거 적용

feat: 이메일, 닉네임 중복 검사 기능 추가

---

src/main/java/com/example/bucketplace/domain/bookmark/controller/BookmarkController.java
src/main/java/com/example/bucketplace/domain/bookmark/controller/docs/BookmarkControllerDocs.java
src/main/java/com/example/bucketplace/domain/bookmark/dto/BookmarkResponseDto.java
src/main/java/com/example/bucketplace/domain/bookmark/entity/Bookmark.java
src/main/java/com/example/bucketplace/domain/bookmark/repository/BookmarkRepository.java
src/main/java/com/example/bucketplace/domain/bookmark/service/BookmarkService.java
src/main/java/com/example/bucketplace/global/exception/ErrorCode.java

* #21 
- 북마크 등록 기능 추가
- Swagger 적용

feat: 북마크 등록 기능 추가

---

src/main/java/com/example/bucketplace/domain/bookmark/controller/BookmarkController.java
src/main/java/com/example/bucketplace/domain/bookmark/controller/docs/BookmarkControllerDocs.java
src/main/java/com/example/bucketplace/domain/bookmark/entity/Bookmark.java
src/main/java/com/example/bucketplace/domain/bookmark/service/BookmarkService.java
src/main/java/com/example/bucketplace/global/exception/ErrorCode.java

* #22 
- 북마크 삭제 기능 추가
- 본인이 등록한 북마크만 제거 가능
- soft delete 적용

feat: 북마크 삭제 기능 추가

---

src/main/java/com/example/bucketplace/domain/product/repository/ProductRepository.java
src/main/java/com/example/bucketplace/domain/review/controller/ReviewController.java
src/main/java/com/example/bucketplace/domain/review/controller/docs/ReviewControllerDocs.java
src/main/java/com/example/bucketplace/domain/review/dto/ReviewRequestDto.java
src/main/java/com/example/bucketplace/domain/review/dto/ReviewResponseDto.java
src/main/java/com/example/bucketplace/domain/review/repository/ReviewRepository.java
src/main/java/com/example/bucketplace/domain/review/service/ReviewService.java
src/main/java/com/example/bucketplace/global/exception/ErrorCode.java

feat: 리뷰 등록 기능

---

src/main/java/com/example/bucketplace/domain/product/controller/ProductController.java
src/main/java/com/example/bucketplace/domain/product/controller/docs/ProductControllerDocs.java
src/main/java/com/example/bucketplace/domain/product/dto/ProductRequestDto.java
src/main/java/com/example/bucketplace/domain/product/dto/ProductResponseDto.java
src/main/java/com/example/bucketplace/domain/product/service/ProductService.java
src/main/java/com/example/bucketplace/global/config/SecurityConfig.java

* #26 
* 전체 상품 조회 기능 구현
* 전체 상품 조회 기능 Swagger 입력
* GetProductResponseDto의 boolean을 Boolean으로 수정
이에 따라, 포스트맨 상에서 isFreeDelivery, isSpecialPrice로 출력되는 점 확인하였습니다. 
* 불분명하거나 직관적이지 않는 변수명, 띄어쓰기 오타, 불필요하게 긴 코드 수정하였습니다.
* 상품 GET 요청은 아직 permitall이 적용되지 않아 토큰이 필요한 상태입니다. 괜찮으시면 제가 SecurityConfig 수정 진행하겠습니다. (수정 컨펌 이후 수정 진행 완료)
* 다음부턴 바로 확인하실 수 있게 포스트맨 출력 화면을 첨부하겠습니다.

feat: 전체 상품 조회 기능

---

build.gradle
src/main/java/com/example/bucketplace/domain/product/repository/ProductRepository.java
src/main/java/com/example/bucketplace/domain/product/scheduler/ProductScheduler.java
src/main/java/com/example/bucketplace/global/config/SchedulerConfig.java

* #6 
- 상품 크롤링 기능 추가
- 1시간마다 실행

feat: 상품 크롤링 기능 추가

---

src/main/java/com/example/bucketplace/domain/review/controller/ReviewController.java
src/main/java/com/example/bucketplace/domain/review/controller/docs/ReviewControllerDocs.java
src/main/java/com/example/bucketplace/domain/review/entity/Review.java
src/main/java/com/example/bucketplace/domain/review/service/ReviewService.java
src/main/java/com/example/bucketplace/global/exception/ErrorCode.java

feat: 리뷰 삭제 기능

---

src/main/java/com/example/bucketplace/domain/bookmark/controller/BookmarkController.java
src/main/java/com/example/bucketplace/domain/bookmark/controller/docs/BookmarkControllerDocs.java
src/main/java/com/example/bucketplace/domain/bookmark/dto/BookmarkResponseDto.java
src/main/java/com/example/bucketplace/domain/bookmark/repository/BookmarkRepository.java
src/main/java/com/example/bucketplace/domain/bookmark/service/BookmarkService.java

* #20 
- 회원 북마크 목록 기능
- 등록일자 기준으로 내림차순 정렬
- 페이징 기능 추가
- 페이지 목록 기본 사이즈 10
```json
{
"status": true,
"message": "회원 북마크 목록 기능",
"data": {
"content": [
{
"id": 2,
"imageUrl": "https://image.ohou.se/i/bucketplace-v2-development/uploads/deals/171090265318492476.jpg?gif=1&w=360&h=360&c=c&q=0.8&webp=1"
},
{
"id": 1,
"imageUrl": "https://image.ohou.se/i/bucketplace-v2-development/uploads/deals/171090265318492476.jpg?gif=1&w=360&h=360&c=c&q=0.8&webp=1"
}
],
"pageable": {
"pageNumber": 0,
"pageSize": 10,
"sort": {
"empty": true,
"unsorted": true,
"sorted": false
},
"offset": 0,
"paged": true,
"unpaged": false
},
"totalPages": 1,
"totalElements": 2,
"last": true,
"size": 10,
"number": 0,
"sort": {
"empty": true,
"unsorted": true,
"sorted": false
},
"numberOfElements": 2,
"first": true,
"empty": …
```

feat: 회원 북마크 목록 기능 추가

---

src/main/java/com/example/bucketplace/domain/bookmark/controller/BookmarkController.java
src/main/java/com/example/bucketplace/domain/bookmark/controller/docs/BookmarkControllerDocs.java
src/main/java/com/example/bucketplace/domain/bookmark/dto/BookmarkResponseDto.java
src/main/java/com/example/bucketplace/domain/bookmark/service/BookmarkService.java

* #42 
- 북마크 등록 확인 여부 기능
- 등록 했으면 true, 안했으면 false를 반환
등록 O 
```json
{
"status": true,
"message": "북마크 등록 여부 확인 기능",
"data": {
"isExist": true
}
}
```
등록 X
```json
{
"status": true,
"message": "북마크 등록 여부 확인 기능",
"data": {
"isExist": false
}
}
```

feat: 북마크 등록 확인 여부 기능

---

src/main/java/com/example/bucketplace/domain/bookmark/controller/BookmarkController.java
src/main/java/com/example/bucketplace/domain/bookmark/controller/docs/BookmarkControllerDocs.java
src/main/java/com/example/bucketplace/domain/bookmark/service/BookmarkService.java

* #46 
* 북마크 페이지 1부터 시작
```http
GET http://localhost:8080/api/v1/members/bookmarks?page=1&size=10
```
```json
{
"status": true,
"message": "회원 북마크 목록 기능",
"data": [
{
"id": 2,
"imageUrl": "https://image.ohou.se/i/bucketplace-v2-development/uploads/deals/171090265318492476.jpg?gif=1&w=360&h=360&c=c&q=0.8&webp=1"
},
{
"id": 1,
"imageUrl": "https://image.ohou.se/i/bucketplace-v2-development/uploads/deals/171090265318492476.jpg?gif=1&w=360&h=360&c=c&q=0.8&webp=1"
}
]
}
```

fix: 북마크 목록 page 값 변경

---

src/main/java/com/example/bucketplace/domain/review/controller/ReviewController.java
src/main/java/com/example/bucketplace/domain/review/controller/docs/ReviewControllerDocs.java
src/main/java/com/example/bucketplace/domain/review/service/ReviewService.java

* #48 
- 리뷰 기능 앤드포인트 수정
- 리뷰 등록: /api/v1/products/{productId}/reviews -> /api/v1/reviews/{productId}
- 리뷰 수정: /api/v1/products/{productId}/reviews/{id} -> /api/v1/reviews/{id}
- 리뷰 삭제: /api/v1/products/{productId}/reviews/{id} -> /api/v1/reviews/{id}

리뷰 앤드포인트 수정

---

src/main/java/com/example/bucketplace/domain/product/controller/ProductController.java
src/main/java/com/example/bucketplace/domain/product/controller/docs/ProductControllerDocs.java
src/main/java/com/example/bucketplace/domain/product/dto/ProductResponseDto.java
src/main/java/com/example/bucketplace/domain/product/repository/ProductRepository.java
src/main/java/com/example/bucketplace/domain/product/service/ProductService.java

feat: 상품 검색 기능

---

src/main/java/com/example/bucketplace/domain/product/controller/ProductController.java
src/main/java/com/example/bucketplace/domain/product/controller/docs/ProductControllerDocs.java
src/main/java/com/example/bucketplace/domain/product/dto/ProductResponseDto.java
src/main/java/com/example/bucketplace/domain/product/service/ProductService.java
src/main/java/com/example/bucketplace/global/config/RedisConfig.java
src/main/java/com/example/bucketplace/global/config/SecurityConfig.java

* #45 
- 상품 실시간 인기 검색어 기능
- 내림차순으로 정렬 됩니다.
- score는 검색 횟수를 뜻합니다.
```json
{
"status": true,
"message": "실시간 상품 검색 순위 기능",
"data": [
{
"keyword": "이불",
"score": 3
},
{
"keyword": "침대",
"score": 2
},
{
"keyword": "베개",
"score": 2
},
{
"keyword": "가방",
"score": 1
}
]
}
```

feat: 상품 실시간 인기 검색어 기능

---

src/main/java/com/example/bucketplace/global/jwt/TokenProvider.java

fix: 쿠키가 들어오지 않던 오류 수정

---

src/main/java/com/example/bucketplace/domain/review/dto/ReviewResponseDto.java

*  #57 
* 프론트 요청에 따라, reviewId를 반환값에 추가하였습니다.

reviewId 반환 추가

---

src/main/java/com/example/bucketplace/domain/product/dto/ProductResponseDto.java
src/main/java/com/example/bucketplace/domain/product/service/ProductService.java
src/main/java/com/example/bucketplace/domain/review/dto/ReviewResponseDto.java
src/main/java/com/example/bucketplace/domain/review/repository/ReviewRepository.java

* #59 
* 전체 상품 조회시 리뷰 개수 및 평점 평균 반환 추가합니다.
* Product 관련 ResponseDto에 countReview, averageRating 추가하였습니다.
다.

feat: 전체 상품 조회시 리뷰 개수 및 평점 평균 반환 추가

---

src/main/java/com/example/bucketplace/domain/member/service/MemberService.java
src/main/java/com/example/bucketplace/global/jwt/TokenProvider.java
src/main/java/com/example/bucketplace/global/security/JwtAuthenticationFilter.java

* #65 
* Access Token에 닉네임 담아주기

feat: access token에 nickname 추가

---

src/main/java/com/example/bucketplace/global/config/CorsMvcConfig.java
src/main/java/com/example/bucketplace/global/config/SecurityConfig.java

fix: cors에 swagger 설정
